feat: PumpyStaking and tests
jmanywhere/pumpy pull request #5
Opened 2023-09-12 20:49 UTC by Gabgrz

2023-09-12 23:17 UTC, jmanywhere commented on src/PumpyStaking.sol
> +        require(amount > 0, "You need to stake at least some tokens");
Usen 
```
if(condition to fail)
    revert CUSTOM_ERROR();
    
```

2023-09-12 23:19 UTC, jmanywhere commented on src/PumpyStaking.sol
> +            claimRewards(true);
When deposit, always claim

2023-09-12 23:20 UTC, jmanywhere commented on src/PumpyStaking.sol
> +    function deposit(uint256 nftId, uint256 amount) external {
agreguen ReentrancyGuard y agreguenle a deposit `nonReentrant` como modifier. 
Para transferir, usen `safeTransferFrom` del ERC721

2023-09-12 23:21 UTC, jmanywhere commented on src/PumpyStaking.sol
> +            claimRewards(true);
not compound

2023-09-12 23:25 UTC, jmanywhere commented on src/PumpyStaking.sol
> +        require(block.timestamp > userInfo[msg.sender].lastAction + 1 days, "You can claim your rewards only once per day");
hagan un chequeo de
```
if block.timestamp <= lastAction)
    revert CUSTOM_ERROR()
```

Los usuarios pueden hacer claim en cualquier momento, aunque haya pasado solamente 1 segundo

2023-09-12 23:25 UTC, jmanywhere commented on src/PumpyStaking.sol
> +        uint256 rewards = (dailyRewards * timeElapsed) / 86400/*oneDay*/ ;
86400 si es un día, PERO pueden usar esta forma de escritura para facilidad: `1 days`

2023-09-12 23:26 UTC, jmanywhere commented on src/PumpyStaking.sol
> +        uint256 dailyRewards = (userInfo[msg.sender].depositAmount * pumpRet) / 1000;
hagan el 1000 una constante que se llame `BASE_PERCENT`

2023-09-12 23:26 UTC, jmanywhere commented on src/PumpyStaking.sol
> +        uint256 dailyRewards = (userInfo[msg.sender].depositAmount * pumpRet) / 1000;
Para lectura más facil de qué significa ese 1000
`uint256 private constant BASE_PERCENT = 1000;`

2023-09-12 23:27 UTC, jmanywhere commented on src/PumpyStaking.sol
> +        require(rewardPool() >= rewards, "There are not enough PUMPY tokens to pay rewards");
recuerden que TIENEN QUE pagar los rewards que hayan, aunque no haya suficiente para todos.

2023-09-12 23:28 UTC, jmanywhere commented on src/PumpyStaking.sol
> +        if (isCompound == true) {
Falta emitir evento de Compound aqui

2023-09-12 23:29 UTC, jmanywhere commented on src/PumpyStaking.sol
> +            pumpy.transfer(msg.sender, rewards);
los transfer OUTs o llamadas a terceros contratos SIEMPRE se hacen después de cambiar las variables internas para evitar un ataque de Reentrancy. Todo este bloque de IF/ELSE lo pueden pasar después del `emit Claim`

2023-09-12 23:30 UTC, jmanywhere commented on src/PumpyStaking.sol
> +        nft.transferFrom(address(this), msg.sender, nftId);
los transfers hasta de ULTIMO, en especial el de NFT.

2023-09-12 23:30 UTC, jmanywhere commented on src/PumpyStaking.sol
> +    1. If the user is already staking an NFT, can they make additional deposits on the same NFT?
yes

2023-09-12 23:30 UTC, jmanywhere commented on src/PumpyStaking.sol
> +    2. Are rewards paid off the staked amount or the token balance?
staked amount up to total reward amount

2023-09-12 23:31 UTC, jmanywhere requested changes
En groso modo, hicieron bastantes cosas bien. Revisen los comentarios para mejorar

2023-09-13 05:29 UTC, susguzman commented on src/PumpyStaking.sol
> +        require(amount > 0, "You need to stake at least some tokens");
implemented !

2023-09-13 05:29 UTC, susguzman commented on src/PumpyStaking.sol
> +            claimRewards(true);
done !

2023-09-13 05:36 UTC, susguzman commented on src/PumpyStaking.sol
> +    function deposit(uint256 nftId, uint256 amount) external {
Done !

2023-09-13 05:59 UTC, susguzman commented on src/PumpyStaking.sol
> +        require(block.timestamp > userInfo[msg.sender].lastAction + 1 days, "You can claim your rewards only once per day");
done !

2023-09-13 05:59 UTC, susguzman commented on src/PumpyStaking.sol
> +        uint256 rewards = (dailyRewards * timeElapsed) / 86400/*oneDay*/ ;
done !

2023-09-13 05:59 UTC, susguzman commented on src/PumpyStaking.sol
> +        uint256 dailyRewards = (userInfo[msg.sender].depositAmount * pumpRet) / 1000;
done !

2023-09-13 06:01 UTC, susguzman commented on src/PumpyStaking.sol
> +        if (isCompound == true) {
Es posible agregar el atributo compound al mismo evento de Claim ? Esto para no crear un evento nuevo solo para Claim 

```
event Claim(
        address indexed user,
        uint256 indexed nftId,
        uint256 rewardAmount,
        bool compound 
    );
```

2023-09-13 06:01 UTC, susguzman commented on src/PumpyStaking.sol
> +            pumpy.transfer(msg.sender, rewards);
done!

2023-09-13 06:10 UTC, susguzman commented on src/PumpyStaking.sol
> +        nft.transferFrom(address(this), msg.sender, nftId);
done!

2023-09-14 23:13 UTC, Gabgrz commented
- added estimatedEndTime().
- Refactored and added more tests
- All tests pass

2025-09-07 05:48 UTC, closed without merging